# Generated by Django 5.0.3 on 2024-03-30 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0005_alter_quote_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('born_date', models.CharField(max_length=60)),
                ('born_location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRegField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quoteapp.authorreg')),
            ],
        ),
    ]
